import { roboto } from '../fonts/fonts';
import { unstable_ViewTransition as ViewTransition } from 'react';
import { Metadata } from 'next';
import '@/global.css';
import { PanelProvider } from '@/context/PanelContext';
import { GlobalPanelRenderer } from '@/ui/templates/GlobalPanelRenderer';
import { Providers } from './Providers';
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className}bg-white text-black`}>
        <PanelProvider>
          <ViewTransition name="page">
              <Providers>{children}</Providers>
              <Toaster position='bottom-right' richColors />
          </ViewTransition>
          <GlobalPanelRenderer />
        </PanelProvider>
      </body>
    </html>
  );
}
